services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=video
      - MYSQL_ROOT_PASSWORD=Milan@123
    ports:
      - "3308:3306"

  video-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=videoStream
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/video?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Milan@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true  
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=1000MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=1000MB
    volumes:
      - ./videos:/app/videos
      - ./thumbnails:/app/thumbnails
      - ./hls:/app/hls
    depends_on:
      - db
